### ISSUE TITLE
repeated line on Arbiter.cpp

### ISSUE THREAD

**Issue by lch32111** [erincatto/box2d-lite#1]
Hi Erin. Thank you for sharing your great articles for physics.
I'm studying game physics based on your articles

I found one repeated line on Arbiter.cpp

This is first calculation on 137
https://github.com/erincatto/box2d-lite/blob/d9705826ca1589a1dc9d3c45396f4678f30e70a9/src/Arbiter.cpp#L137

However, it is repeated on 166
https://github.com/erincatto/box2d-lite/blob/d9705826ca1589a1dc9d3c45396f4678f30e70a9/src/Arbiter.cpp#L166

**Comment by erincatto** [comment]
Thanks for reporting this.

This is a required aspect of the solver. The first dv is used to compute the normal impulse. After that is applied dv needs to be updated for the tangent (friction) impulse. I recommend you try removing the second computation and see how the solver behaves.

**Comment by lch32111** [comment]
Thanks for answering this. I get to know now why it is there.

And I have one more to report to you.
https://github.com/erincatto/box2d-lite/blob/d9705826ca1589a1dc9d3c45396f4678f30e70a9/src/Collide.cpp#L170-L171

On int Collide(Contact* contacts, Body* bodyA, Body* bodyB) function,
you define each col of rotation matrices from bodyA and bodyB.
But you don't use it.

I know it does not affect the performance and the behavior of box2d.
But I just want to clear it.

**Comment by erincatto** [comment]
Thanks, fixed in 3e3dccb06d1e92ae40ed2e885125430122999769
